language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t oliverm316/dockerized_cuttevents_backoffice -f Dockerfile.dev .

script:
  - docker run oliverm316/dockerized_cuttevents_backoffice npm run test -- --coverage
